### PR TITLE
fixes

### LINKED ISSUE #500: [Bug]: primary Pubky logo renders poorly
### Describe the bug

Pubky logo looks overly jaggy and the finer parts are not rendering consistently. I'm not sure if this has something to do with the code and rendering itself, or if we need to try a png instead, or make it larger so the crown details are symmetrically rendered consistently. 

### Reproduce

_No response_

### Screenshots / Recording

image

### Web Browser

_No response_

### Pubky App Version

Chrome

### Console log output

_No response_

### LINKED ISSUE #668: [Bug]: Image stretched when attaching to new article
### Describe the bug

In the New Article modal, when an image is added it can be stretched.  We should display it in proportion, as is done once it appears in the feed.

### Reproduce

1. Go to create a new article post
2. Add file, use an image that is much taller than it is wide (attached example below)
3. Observe is is stretched to fill the width of the field in the modal

### Screenshots / Recording

Screenshot_20241121_144400

Screenshot_20241121_144910

Alt Text

### Web Browser

Version 1.73.89 Chromium: 131.0.6778.69 (Official Build) (64-bit)

### Pubky App Version

449ee310ca5341ad9a3361a46396b51998f9d842

### Console log output

_No response_

### LINKED ISSUE #726: [Feature]: load more "Hot Posts"
### Describe the problem

Infinite scrolling for "Hot Post" section in `/hot` page.

https://github.com/user-attachments/assets/049639af-a0a3-4884-9fb2-12aaa2c510b1

### LINKED ISSUE #736: [Bug]: Typo is not the correct one with Firefox
### Describe the bug

Screenshot 2024-12-05 at 12 38 15

### Reproduce

_No response_

### Screenshots / Recording

_No response_

### Web Browser

Firefox

### Pubky App Version

v2.0.0

### Console log output

_No response_

### LINKED ISSUE #781: [Feature]: Longer article titles
### Describe the problem

Sometimes 30 chars is not enough, but there is space.

### Describe the solution

Increase this limit to 50?

### Additional context

Screenshot 2024-12-19 at 16 56 53

### PR DESCRIPTION
**Pull request by flaviomoceri**
1. fix image stretched article + dynamic year
2. fix pubky logo poorly
3. load more hot posts (recent as sort filter for now)
4. Trying to fix firefox font issue
5. Increase size title for article + SEO + links post

### CODE REVIEW

File: apps/intro/pages/index.tsx [hunk 1]
```diff
@@ -75,7 +76,7 @@ export default function Index() {
           variant="small"
           className="fixed bottom-12 text-[13.5px] text-opacity-30 font-normal"
         >
-          Synonym Software Ltd. ©2024.
+          Synonym Software Ltd. ©{currentYear || 2025}.
```
Comment (MiguelMedeiros) [inline apps/intro/pages/index.tsx]:
```suggestion
          Synonym Software Ltd. ©{currentYear}.
```
The fallback || 2025 is unnecessary because new Date().getFullYear() always returns a valid year.

File: apps/web/app/onboarding/components/_Content.tsx [hunk 2]
```diff
@@ -176,7 +177,7 @@ export default function Index() {
             variant="small"
             className="text-[13.5px] text-opacity-30 font-normal"
           >
-            Synonym Software Ltd. ©2024.
+            Synonym Software Ltd. ©{currentYear || 2025}.
```
Comment (MiguelMedeiros) [inline apps/web/app/onboarding/components/_Content.tsx]:
```suggestion
            Synonym Software Ltd. ©{currentYear}.
```

same here
