### PR TITLE
fix: login with PubkyRing handle issues

### LINKED ISSUE #1375: [Feature]: Display error when failed to sign in with pubky-ring
### Describe the problem

When scanning the QR to sign in with pubky-ring, if the session cannot be found the QR simply cycles with no UI error.

### Describe the solution

When the cause is 404 for the session we should display an error to the user because it is probably that retrying will not work. We display and error when this happens when using file to sign in.

### Additional context

Image

### LINKED ISSUE #1379: [Bug]: QR request loop is too fast on failure (high CPU load)
### Describe the bug

I left my laptop without wifi connection and it started to take off with the rate its fan was spinning.
The QR code on the sign-in page cycles rapidly.

We should add a sleep in to failed connections to http-relay to avoid this unnecessary processing.
See [_SignIn](https://github.com/pubky/pubky-app/blob/dev/src/app/sign-in/Card/_SignIn.tsx#L50) and [_Join](https://github.com/pubky/pubky-app/blob/dev/src/app/onboarding/sign-in/Card/_Join.tsx#L50C9-L50C30)

### Reproduce

1. Sit on sign in page with no network connection
2. Observe the QR rapidly cycling as it fails to communicate with the http-relay

### Screenshots / Recording

In this video, my CPU is idling below 68C with the fan at around 30% but when I cut my wifi network it jumps to near 80% and 65% fan.

https://github.com/user-attachments/assets/8b7e5f8e-8917-42fc-99b4-396d5d82d183

### Web Browser

Version 1.76.74 Chromium: 134.0.6998.89 (Official Build) (64-bit)

### Pubky App Version

4dfc25a

### Console log output

```shell

```

### PR DESCRIPTION
**Pull request by flaviomoceri**

### CODE REVIEW

File: src/app/onboarding/sign-in/Card/_Join.tsx [hunk 1]
```diff
@@ -67,11 +67,16 @@ export default function Join() {
...
+            setAuthUrl('');
+            setLoginError('No internet connection. Please try again.');
+            return;
+          } else {
+            setLoginError('Failed to login.');
           }
+
           handleGenerateAuthUrl(signal);
         } catch (error) {
           console.error('Unexpected error occurred:', error);
```
Comment (MiguelMedeiros) [inline src/app/onboarding/sign-in/Card/_Join.tsx]: We should not have this retry in the try catch error. 
We could just add a button to refresh the QRcode after timeout. This would prevent so many bugs.

Comment (flaviomoceri) [reply src/app/onboarding/sign-in/Card/_Join.tsx]: Done, give a look now, we are trying to generate it automatically, so the user doesn't need to refresh using a button, but could be an idea, whatever error we receive from the catch we show up the error and a button to generate a new authUrl

**Comment by catch-21** [comment]
LGTM 👍

**Review by catch-21 — APPROVED** [review]

**Review by MiguelMedeiros — APPROVED** [review]
