### PR TITLE
fix: show avatar only in tagged section

### LINKED ISSUE #1661: [Bug]: Profile persists in all tabs in mobile
### Describe the bug

see image

### Reproduce

Image

### Screenshots / Recording

_No response_

### Web Browser

_No response_

### Pubky App Version

_No response_

### Console log output

```shell

```

### PR DESCRIPTION
**Pull request by flaviomoceri**

### CODE REVIEW

File: src/app/profile/[creatorPubky]/components/_CreatorpubkyLayout.tsx [hunk 1]
```diff
@@ -77,23 +79,25 @@ export default function CreatorpubkyLayout({
...
             />
-            <div className="w-full rounded-2xl p-6 lg:p-0 bg-white lg:bg-transparent bg-opacity-10 flex flex-col text-center lg:flex-row items-center gap-3 lg:gap-14 relative">
-              {profile?.details?.id && (
-                <Profile.Avatar
-                  id={profile?.details?.id}
-                  isCensored={Utils.isProfileCensored(profile)}
-                  className="lg:pl-12 cursor-pointer"
-                  username={profile?.details?.name || Utils.minifyPubky(creatorPubky)}
-                  onClick={() => setIsAvatarOpen(true)}
+            {(activeTab === 6 || !isMobile) && (
```
Comment (catch-21) [inline src/app/profile/[creatorPubky]/components/_CreatorpubkyLayout.tsx]: Works but I don't think we should do `activeTab === 6` as it could change when tabs are addedremoved/reordered.

Can define this and call it instead:
```
const shouldShowAvatarSection = () => {
  const foundTab = Profile.FilterTabs.tabs.find((tab) => tab.id === activeTab);
  return foundTab?.key === 'tagged' || !isMobile;
};
  ```

**Comment by flaviomoceri** [comment]
done @catch-21

**Review by catch-21 — APPROVED** [review]

**Review by catch-21 — APPROVED** [review]
