### PR TITLE
fix files-type

### LINKED ISSUE #634: [Feature]: Handle TIFF image in posts
### Describe the problem

An attached TIFF image file doesn't render in the post input area, nor does it display correctly in the feed.

Alt Text

Alt Text

[file_example_TIFF_5MB.zip](https://github.com/user-attachments/files/17805294/file_example_TIFF_5MB.zip)

### Describe the solution

Like Github, we may not want to support presenting every media format. We could:
- treat this extension as a regular file and not display it
- prevent files with this extension from being uploaded
- convert TIFF to JPG in the backend for presentation

### Additional context

What Github shops if you try to attach TIFF image to issue:
Screenshot_20241118_192632

### LINKED ISSUE #635: [Feature]: Support AVI video format in posts
### Describe the problem

AVI videos show the media player when uploaded but do not play.

Screenshot_20241118_193007

### Describe the solution

Add support for AVI so it plays
or
Don't show the media player for this file format

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by flaviomoceri**

### CODE REVIEW

**Review by MiguelMedeiros — APPROVED** [review]

File: libs/utils-shared/src/lib/Helper/FileType/_video.ts [hunk 1]
```diff
@@ -0,0 +1 @@
+export const supportedVideoTypes = ['video/mp4', 'video/webm', 'video/ogg'];
```
Comment (catch-21) [inline libs/utils-shared/src/lib/Helper/FileType/_video.ts:1]: what about `mov`? it works in the app before this change

Comment (catch-21) [reply libs/utils-shared/src/lib/Helper/FileType/_video.ts:1]: https://github.com/pubky/pubky-app/pull/643

**Comment by catch-21** [comment]
Verified in 2074afe40666fd912b0a5e86a395525de8a59464
