### PR TITLE
fix: includeImage in charsCounter article

### LINKED ISSUE #1503: [Bug]: Images embedded in article are not included in the size counter
### Describe the bug

Raised off the back of https://github.com/pubky/pubky-app/issues/1305#issuecomment-2866332172

When embedding an image in an article, it contributes to the size limit (40_000 byte) but the counter does not take it in to consideration.

We should try to include the image size in the counter to make it clearer to the user how much space the image is taking up compared with the text.

### Reproduce

1. Go to create a new article
2. Add some text to the content
3. Add a small image to the content area (not talking about the cover image)
4. Observe the image in inserted but the counter does not increase

### Screenshots / Recording

Image

### Web Browser

_No response_

### Pubky App Version

710cc9b6c1f5d60330e1a17dd42dc27371a8eb18

### Console log output

```shell

```

### PR DESCRIPTION
**Pull request by flaviomoceri**

### CODE REVIEW

**Review by catch-21 — CHANGES_REQUESTED** [review]
See https://github.com/pubky/pubky-app/issues/1503#issuecomment-2884268040

**Comment by catch-21** [comment]
These image scaling changes are good. We should now just remove the UI counter from the footer area for a clean and simple UX.

**Comment by flaviomoceri** [comment]
@catch-21 done, for now i just hide the counter on UI level, to avoid if someone changes their mind and we have to add it again somehow

File: src/components/CreateContent/Section/_FooterArea.tsx [hunk 1]
```diff
@@ -63,8 +63,8 @@ export default function FooterArea({
   maxLength = 1000,
   setShowModalPost,
   isError,
-  loading,
-  charCountArticle
+  loading
+  // charCountArticle
```
Comment (catch-21) [inline src/components/CreateContent/Section/_FooterArea.tsx:67]: remove comment

**Review by catch-21 — APPROVED** [review]
